#!/usr/bin/env python

import os

x = """
DROSERACEAE --> flore.main.01.jpg
BUTOMACEAE --> flore.main.02.jpg
FRANKENIACEAE --> flore.main.03.jpg
APOCYNACEAE --> flore.main.04.jpg
Sedum_acre_86b31e2b.jpg --> flore.main.05.jpg
BUXACEAE --> flore.main.06.jpg
cp.photos.sh --> flore.main.07.jpg
ARALIACEAE --> flore.main.08.jpg
CORNACEAE --> flore.main.09.jpg
SAXIFRAGACEAE --> flore.main.10.jpg
AIZOACEAE --> flore.main.11.jpg
THYMELAEACEAE --> flore.main.12.jpg
EPHEDRACEAE --> flore.main.13.jpg
TAXACEAE --> flore.main.14.jpg
SCHEUCHZERIACEAE --> flore.main.15.jpg
CACTACEAE --> flore.main.16.jpg
HYMENOPHYLLACEAE --> flore.main.17.jpg
ISOETACEAE --> flore.main.18.jpg
PRIMULACEAE --> flore.main.19.jpg
MORACEAE --> flore.main.20.jpg
Sedum_acre_70534_323104.jpg --> flore.main.21.jpg
GERANIACEAE --> flore.main.22.jpg
LIMNANTHACEAE --> flore.main.23.jpg
EQUISETACEAE --> flore.main.24.jpg
PAPAVERACEAE --> flore.main.25.jpg
MELANTHIACEAE --> flore.main.26.jpg
SAPINDACEAE --> flore.main.27.jpg
FABACEAE --> flore.main.28.jpg
Sedum_acre_56933_261605.jpg --> flore.main.29.jpg
ORCHIDACEAE --> flore.main.30.jpg
Sedum_acre_58731_268773.jpg --> flore.main.31.jpg
STYRACACEAE --> flore.main.32.jpg
Sedum_acre_56933_261603.jpg --> flore.main.33.jpg
SCROPHULARIACEAE --> flore.main.34.jpg
Sedum_acre_16e4f136.jpg --> flore.main.35.jpg
CANNABACEAE --> flore.main.36.jpg
POACEAE --> flore.main.37.jpg
COLCHICACEAE --> flore.main.38.jpg
CYTINACEAE --> flore.main.39.jpg
list_orhcids --> flore.main.40.jpg
ERICACEAE --> flore.main.41.jpg
POSIDONIACEAE --> flore.main.42.jpg
BORAGINACEAE --> flore.main.43.jpg
Sedum_acre_26615_125380.jpg --> flore.main.44.jpg
HYDROCHARITACEAE --> flore.main.45.jpg
BALSAMINACEAE --> flore.main.46.jpg
more --> flore.main.47.jpg
PLATANACEAE --> flore.main.48.jpg
BETULACEAE --> flore.main.49.jpg
DRYOPTERIDACEAE --> flore.main.50.jpg
OLEACEAE --> flore.main.51.jpg
PLUMBAGINACEAE --> flore.main.52.jpg
inpn --> flore.main.53.jpg
ELAEAGNACEAE --> flore.main.54.jpg
PASSIFLORACEAE --> flore.main.55.jpg
LYTHRACEAE --> flore.main.56.jpg
MOLLUGINACEAE --> flore.main.57.jpg
PAEONIACEAE --> flore.main.58.jpg
ONAGRACEAE --> flore.main.59.jpg
Sedum_acre_56933_261606.jpg --> flore.main.60.jpg
Sedum_acre_26615_125384.jpg --> flore.main.61.jpg
OROBANCHACEAE --> flore.main.62.jpg
IRIDACEAE --> flore.main.63.jpg
POLYGONACEAE --> flore.main.64.jpg
WOODSIACEAE --> flore.main.65.jpg
ULMACEAE --> flore.main.66.jpg
POLEMONIACEAE --> flore.main.67.jpg
JUGLANDACEAE --> flore.main.68.jpg
RUBIACEAE --> flore.main.69.jpg
HYPERICACEAE --> flore.main.70.jpg
VITACEAE --> flore.main.71.jpg
GESNERIACEAE --> flore.main.72.jpg
VIOLACEAE --> flore.main.73.jpg
Sedum_acre_56933_261604.jpg --> flore.main.74.jpg
Sedum_acre_d15a4fa3.jpg --> flore.main.75.jpg
ASPLENIACEAE --> flore.main.76.jpg
RANUNCULACEAE --> flore.main.77.jpg
THELYPTERIDACEAE --> flore.main.78.jpg
CAMPANULACEAE --> flore.main.79.jpg
CYPERACEAE --> flore.main.80.jpg
NARTHECIACEAE --> flore.main.81.jpg
Sedum_acre_70534_323109.jpg --> flore.main.82.jpg
URTICACEAE --> flore.main.83.jpg
ROSACEAE --> flore.main.84.jpg
APONOGETONACEAE --> flore.main.85.jpg
ALISMATACEAE --> flore.main.86.jpg
TYPHACEAE --> flore.main.87.jpg
JUNCACEAE --> flore.main.88.jpg
DIOSCOREACEAE --> flore.main.89.jpg
CELASTRACEAE --> flore.main.90.jpg
SALICACEAE --> flore.main.91.jpg
Sedum_acre_58731_268774.jpg --> flore.main.92.jpg
SOLANACEAE --> flore.main.93.jpg
PINACEAE --> flore.main.94.jpg
SMILACACEAE --> flore.main.95.jpg
POLYPODIACEAE --> flore.main.96.jpg
PORTULACACEAE --> flore.main.97.jpg
PHYTOLACCACEAE --> flore.main.98.jpg
PLANTAGINACEAE --> flore.main.99.jpg
RESEDACEAE --> flore.main.100.jpg
BERBERIDACEAE --> flore.main.101.jpg
LINACEAE --> flore.main.102.jpg
LENTIBULARIACEAE --> flore.main.103.jpg
TOFIELDIACEAE --> flore.main.104.jpg
ARACEAE --> flore.main.105.jpg
ELATINACEAE --> flore.main.106.jpg
HALORAGACEAE --> flore.main.107.jpg
LAURACEAE --> flore.main.108.jpg
LINDERNIACEAE --> flore.main.109.jpg
ACORACEAE --> flore.main.110.jpg
CUPRESSACEAE --> flore.main.111.jpg
BLECHNACEAE --> flore.main.112.jpg
ACANTHACEAE --> flore.main.113.jpg
ASTERACEAE --> flore.main.114.jpg
SALVINIACEAE --> flore.main.115.jpg
CAPRIFOLIACEAE --> flore.main.116.jpg
VERBENACEAE --> flore.main.117.jpg
CAPPARACEAE --> flore.main.118.jpg
ANACARDIACEAE --> flore.main.119.jpg
caterogies.txt --> flore.main.120.jpg
APIACEAE --> flore.main.121.jpg
MALVACEAE --> flore.main.122.jpg
LAMIACEAE --> flore.main.123.jpg
AQUIFOLIACEAE --> flore.main.124.jpg
TAMARICACEAE --> flore.main.125.jpg
AMARANTHACEAE --> flore.main.126.jpg
XANTHORRHOEACEAE --> flore.main.127.jpg
RUTACEAE --> flore.main.128.jpg
POLYGALACEAE --> flore.main.129.jpg
LILIACEAE --> flore.main.130.jpg
MENYANTHACEAE --> flore.main.131.jpg
ZYGOPHYLLACEAE --> flore.main.132.jpg
AMARYLLIDACEAE --> flore.main.133.jpg
BRASSICACEAE --> flore.main.134.jpg
NYMPHAEACEAE --> flore.main.135.jpg
CRASSULACEAE --> flore.main.136.jpg
SELAGINELLACEAE --> flore.main.137.jpg
ZOSTERACEAE --> flore.main.138.jpg
GROSSULARIACEAE --> flore.main.139.jpg
CORIARIACEAE --> flore.main.140.jpg
FAGACEAE --> flore.main.141.jpg
EUPHORBIACEAE --> flore.main.142.jpg
POTAMOGETONACEAE --> flore.main.143.jpg
JUNCAGINACEAE --> flore.main.144.jpg
CARYOPHYLLACEAE --> flore.main.145.jpg
RUPPIACEAE --> flore.main.146.jpg
photos_a_verifier.lst --> flore.main.147.jpg
SIMAROUBACEAE --> flore.main.148.jpg
RHAMNACEAE --> flore.main.149.jpg
DENNSTAEDTIACEAE --> flore.main.150.jpg
MARSILEACEAE --> flore.main.151.jpg
STAPHYLEACEAE --> flore.main.152.jpg
MYRICACEAE --> flore.main.153.jpg
MYRTACEAE --> flore.main.154.jpg
ARISTOLOCHIACEAE --> flore.main.155.jpg
ASPARAGACEAE --> flore.main.156.jpg
GENTIANACEAE --> flore.main.157.jpg
CUCURBITACEAE --> flore.main.158.jpg
CISTACEAE --> flore.main.159.jpg
LYCOPODIACEAE --> flore.main.160.jpg
HYDRANGEACEAE --> flore.main.161.jpg
CONVOLVULACEAE --> flore.main.162.jpg
Sedum_acre_26615_125381.jpg --> flore.main.163.jpg
AZOLLACEAE --> flore.main.164.jpg
OPHIOGLOSSACEAE --> flore.main.165.jpg
SANTALACEAE --> flore.main.166.jpg
OSMUNDACEAE --> flore.main.167.jpg
PTERIDACEAE --> flore.main.168.jpg
250065868.fona --> flore.main.169.jpg
OXALIDACEAE --> flore.main.170.jpg
CYMODOCEACEAE --> flore.main.171.jpg
CERATOPHYLLACEAE --> flore.main.172.jpg
ADOXACEAE --> flore.main.173.jpg
"""

for item in x.split("\n"):
    if item.strip():
        print(item)
        n1,trash,n2 = item.split()
        os.rename(n2,n1)
#    
